dist: trusty
sudo: required

language: cpp

os: linux
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-stretch-10
        packages:
            - clang++-10

compiler: 
    - gcc
    - clang

env:
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

install:
    - source CI/travis/install.sh

script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
    - cmake --build .
    - ctest --output-on-failure