dist: trusty
sudo: required

language: cpp

os: linux

compiler: 
    - gcc
    - clang

env:
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

install:
    - source CI/travis/install.sh

script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU -DLIBCXX_INSTALL_FILESYSTEM_LIBRARY=YES -DLIBCXX_INSTALL_EXPERIMENTAL_LIBRARY=YES
    - cmake --build .
    - ctest --output-on-failure