dist: trusty
sudo: required

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-3.9
    packages:
      - clang-3.9
      - libc++-dev
      - libc++abi-dev


language: cpp

os: linux

compiler: 
    - gcc
    - clang

env:
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

before_install:
    - source CI/travis/install.sh

script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
    - cmake --build .
    - ctest --output-on-failure